
name: deploy-blog

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: blog/vuepress-theme-hope/package.json
          node-version: 20

      - name: Install pnpm
        working-directory: blog/vuepress-theme-hope
        run: npm install -g pnpm

      - name: Install dependencies
        working-directory: blog/vuepress-theme-hope
        run: pnpm install

      - name: Build
        working-directory: blog/vuepress-theme-hope
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm run docs:build
          touch src/.vuepress/dist/.nojekyll
          

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: blog/vuepress-theme-hope/src/.vuepress/dist
